version: '3.8'

services:
  lab1-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab1-container
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
